force-app/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <label>Trade</label>
    <nameField>
        <displayFormat>TR-{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade__c/fields/Buy_Currency__c.field-meta.xml
<CustomField>
    <fullName>Buy_Currency__c</fullName>
    <label>Buy Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currencies</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Sell_Currency__c.field-meta.xml
<CustomField>
    <fullName>Sell_Currency__c</fullName>
    <label>Sell Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currencies</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Currencies.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>GBP</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <masterLabel>Currencies</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestNewTradeController.cls
@isTest
public class TestNewTradeController {
    
    static testMethod void testGetTradeInfo() {
        Test.setMock(HttpCalloutMock.class, new API_ResponseMock());
        Test.startTest();
        Decimal rate = NewTradeController.getTradeInfo('USD', 'USD');
        Test.stopTest();
        
        System.assertEquals(1, rate);
    }
    
    static testMethod void testgetAllTrades() {
        Trade__c t1 = new Trade__c();
        Trade__c t2 = new Trade__c();
        
        insert t1;
        insert t2;
        
        Test.startTest();
        List<Trade__c> tList = NewTradeController.getAllTrades();
        Test.stopTest();

        System.assertEquals(2, tList.size());
    }
    
    static testMethod void testcreateNewTrade() {
        Test.startTest();
        Trade__c t = NewTradeController.createNewTrade('USD', 'EUR', 10, 1.2);
        Test.stopTest();
        
        System.assertEquals('USD', t.Sell_Currency__c);
        System.assertEquals('EUR', t.Buy_Currency__c);
        System.assertEquals(10, t.Sell_Amount__c);
        System.assertEquals(1.2, t.Rate__c);
        System.assertEquals(12, t.Buy_Amount__c);
    }
}